### ISSUE TITLE
User story: upload images

### ISSUE THREAD

**Issue by yicao928** [david-fisher/320-F19-Track-I#29]
Grower Steven wants to know about apple trees health condition. He takes a picture of one leaf on the apple tree he wants to know about, then open the OrchardWatch website by his phone or computer browser. He login to the OrchardWatch website(story 2). At homepage, he clicks to button “researcher dashboard” and go to this new page. There is a “upload photograph” link. Steven click that link, he then goes to another page that can upload the photo he took. He chooses“Upload”, then there is a new window appears so that he can select the photo he wants to upload. He chooses the photo he took and there is a check mark to show which photo he chooses. By clicking “upload”, the photo uploaded to the website and Steven go back to previous page. After a few seconds, his photo shows up and a few lines of words tell him the probability that tree has disease.
(For growers and researchers)

**Comment by khesemeyerumass** [comment]
Stephanie is an orchard grower who wants to upload pictures of specific clusters on apple trees within the orchard. These pictures should be ones taken on the OrchardWatch app and must include the clusters AprilTag on it. She goes onto the OrchardWatch website via a computer and then logs into her account. On the home page, Stephanie selects the “Research Data” button, which opens a new page. She then chooses the “Upload Photograph” button and another page is open. On this page, there are boxes that Stephanie fills out that are for specific information related to her image including the number specifying the exact tree she is taken a picture of, the cluster number the image is referring to, and the date when the picture was taken. Also, there is an “Select Image” button which opens a window that allows her to select the specific image from her computer. Once Stephanie fills in the boxes and chooses her image, she clicks the “Upload” button and then the previous page is opened, which showcases the newly uploaded image. Stephanie then sees a drop-down box with options about which machine learning algorithm should be applied to identify the apple and its various attributes, as well as calculate data from the previous image with the supposedly same apple from the date of last recording (these features will only be available to researchers).
