### ISSUE TITLE
User stories General Public

### ISSUE THREAD

**Issue by jmerullo** [david-fisher/320-F19-Track-I#3]

**Comment by AvocadoGoast** [comment]
General Public:
1)
Robert wants to see what Orchard Watch is all about. So he goes to website of the Orchard Watch web application. Here he sees the home page. There is an option to login, but he’s just trying to get information. He sees a link labelled “About” or something, and after following the link, he is on the introductory information page about Orchard Watch and can read the goals and mission statement, as well as learn what kind of research is being conducted.

2)
Robert wants to plan a visit to the Orchard. He remembers that the website has the information for visiting hours and the address. He goes into his browser and goes to the Orchard Watch website. At the bottom of the home page he sees contact information and the address he needs. At the top of the page is a link that says “Visit Us” or something of the like. He follows that link and is directed to a page where the visiting hours of the week are shown with the address and contact information for more questions. Also shown is a promotion for visiting.

3)
Robert has planned a visit to the orchard. But he wants to know if there are any special promotions going on. He remembers seeing a promotional display on the website he saw last time and goes to check it. He goes to the home page, and on the home page is a block dedicated to current events and shown is the promotion (coupon or ticket?).
