### ISSUE TITLE
Create Wiki Page

### ISSUE THREAD

**Issue by ZachSchaffer** [david-fisher/320-F19-Track-I#96]
Create a wiki page for your team

**Comment by khesemeyerumass** [comment]
Hey Zach! I just wanted to ask if our wiki page should be named anything specific?

**Comment by ZachSchaffer** [comment]
> Hey Zach! I just wanted to ask if our wiki page should be named anything specific?

Just follow the lead of the other wiki pages, your team name and number will suffice for the title, and in the description list your names and roles.
